import { Inter } from 'next/font/google'
import './globals.css'
import HeaderWrapper from '@/components/navigation/HeaderWrapper'
import Badges from '@/components/util/Badges'
import Sitemap from '@/components/util/Sitemap'
import Footer from '@/components/util/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} text-lg tracking-wide`}>
        <HeaderWrapper />
        <div className='relative top-[5rem]'>{children}</div>
        <Badges />
        <Sitemap />
        <Footer />
      </body>
    </html>
  )
}
